import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { SidebarProvider } from "@/context/contextSidebar";
import { ChatboxProvider } from "@/context/contextChatbox";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "OCR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ChatboxProvider>
          <SidebarProvider>
            <Sidebar />
            <main className="min-h-screen bg-gradient-to-br from-[#0a0a0f] via-[#0f0f0f] to-[#0f0a10]">
              {children}
            </main>
          </SidebarProvider>
        </ChatboxProvider>
      </body>
    </html>
  );
}
